appName: wordpress
replicaCount: 2

image:
  repository: wordpress
  tag: 7.1.2-apache

containerPort: 80

service:
  type: LoadBalancer
  port: 80

db:
  host: ""
  user: ""
  name: ""
  password: ""

scName: efs-sc