name: "Helm Install"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target Environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod
      region:
        description: "AWS Region"
        required: true
        default: "eu-west-3"
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform-apply.yml
    with:
      environment: ${{ inputs.environment }}
      region: ${{ inputs.region }}
    secrets: inherit

  helm-install:
    needs: terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ inputs.region }}

      - name: Install Helm
        uses: azure/setup-helm@v5
        id: install

      - name: Configure kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ needs.terraform.outputs.eks_cluster_name }} --region ${{ inputs.region }}

      - name: Install storage-class Helm Chart
        run: |
          helm upgrade --install storage-class ./helm/storage-class \
            --set efsFileSystemId=${{ needs.terraform.outputs.efs_id }} \
            --wait
            
      - name: Install wordpress Helm Chart
        run: |
          helm upgrade --install wordpress ./helm/wordpress \
            --set db.host=${{ needs.terraform.outputs.rds_address }} \
            --set db.user=${{ needs.terraform.outputs.rds_username }} \
            --set db.name=${{ needs.terraform.outputs.rds_name }} \
            --set db.password=${{ needs.terraform.outputs.rds_password }} \
            --wait