name: "Helm Lint"

on:
  workflow_call:
  push:
  pull_request:

jobs:
  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Lint Helm Charts (storage-class)
        run: helm lint ./helm/storage-class

      - name: Lint Helm Charts (wordpress)
        run: helm lint ./helm/wordpress