name: "Terraform Lint & Validate"

on:
  push:
  pull_request:

jobs:
  terraform-lint-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3

      - name: Check Terraform Format
        run: terraform fmt -recursive -check

      - name: Validate Bootstrap
        working-directory: ./terraform/bootstrap
        run: |
          terraform init -backend=false
          terraform validate
