name: "Terraform Apply"

on:
  workflow_call:
    inputs:
      environment:
        description: "Target Environment"
        required: true
        default: "dev"
        type: string
      region:
        description: "AWS Region"
        required: true
        default: "eu-west-3"
        type: string
    outputs:
      eks_cluster_name:
        description: "EKS Cluster Name"
        value: ${{ jobs.terraform.outputs.eks_cluster_name }}
      efs_id:
        description: "EFS ID"
        value: ${{ jobs.terraform.outputs.efs_id }}
      rds_name:
        description: "RDS Name"
        value: ${{ jobs.terraform.outputs.rds_name }}
      rds_endpoint:
        description: "RDS Endpoint"
        value: ${{ jobs.terraform.outputs.rds_endpoint }}
      rds_username:
        description: "RDS Username"
        value: ${{ jobs.terraform.outputs.rds_username }}
  workflow_dispatch:
    inputs:
      environment:
        description: "Target Environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod
      region:
        description: "AWS Region"
        required: true
        default: "eu-west-3"
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: "Terraform Lint"
        uses: ./.github/workflows/terraform-lint.yml

      - name: "Helm Lint"
        uses: ./.github/workflows/helm-lint.yml

  terraform-apply:
    runs-on: ubuntu-latest
    needs: lint
    outputs:
      eks_cluster_name: ${{ steps.terraform-output.outputs.eks_cluster_name }}
      efs_id: ${{ steps.terraform-output.outputs.efs_id }}
      rds_name: ${{ steps.terraform-output.outputs.rds_name }}
      rds_endpoint: ${{ steps.terraform-output.outputs.rds_endpoint }}
      rds_username: ${{ steps.terraform-output.outputs.rds_username }}

    steps:
      - uses: actions/checkout@v7

      - name: AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ inputs.region }}

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Terraform Init
        working-directory: ./terraform/infra
        run: terraform init

      - name: Terraform Workspace Select
        working-directory: ./terraform/infra
        run: |
          terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }}

      - name: Terraform Apply
        working-directory: ./terraform/infra
        run: |
          terraform apply -var-file=./env/${{ inputs.environment }}.tfvars -auto-approve

      - name: Terraform Output
        id: terraform-output
        working-directory: ./terraform/infra
        run: |
          echo "eks_cluster_name=$(terraform output -raw eks_cluster_name)" >> $GITHUB_OUTPUT"
          echo "efs_id=$(terraform output -raw efs_id)" >> $GITHUB_OUTPUT"
          echo "rds_name=$(terraform output -raw rds_name)" >> $GITHUB_OUTPUT"
          echo "rds_endpoint=$(terraform output -raw rds_endpoint)" >> $GITHUB_OUTPUT"
          echo "rds_username=$(terraform output -raw rds_username)" >> $GITHUB_OUTPUT"